version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    volumes:
      - ./api:/app/api
    environment:
      - PORT=${PORT:-8000}
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VERIFY_TOKEN=${VERIFY_TOKEN}
      - WH_TOKEN=${WH_TOKEN}
      - WH_PHONE_ID=${WH_PHONE_ID}
      - X_ADMIN_TOKEN=${X_ADMIN_TOKEN}
    depends_on:
      - db
      - redis
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=luminiteq
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
  postgres_data:
