name: Dev DB migrations

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  migrate:
    name: Alembic upgrade (dev database)
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure database URL secret is present
        run: |
          if [ -z "${DATABASE_URL}" ]; then
            echo "DEV_DATABASE_URL secret is not configured" >&2
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt

      - name: Run Alembic migrations
        run: |
          alembic -c api/alembic.ini upgrade head
