name: Dev DB Alembic Migrate

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  migrate:
    name: Run Alembic upgrade on dev DB
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt

      - name: Run Alembic migrations
        working-directory: api
        run: alembic upgrade head
