name: Migrate Dev DB

on:
  workflow_dispatch: {}
  push:
    branches: [ "dev" ]

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (alembic + driver)
        run: |
          python -m pip install --upgrade pip
          if [ -f api/requirements.txt ]; then pip install -r api/requirements.txt; else pip install alembic "psycopg[binary]" SQLAlchemy; fi

      - name: Run Alembic upgrade (dev)
        run: |
          python -m alembic -c api/alembic.ini upgrade head
